/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/q45IPwLqiw4
 */
import { Badge } from "@/components/ui/badge";

interface WhoamiProps {
  nickname: string;
  expiration: string;
  groups: string[];
}

export function Whoami({ nickname, expiration, groups }: WhoamiProps) {
  return (
    <div className="flex flex-col min-h-screen justify-center align-center">
      <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-md max-w-md mx-auto ">
        <h2 className="text-2xl font-bold mb-2 text-gray-900 dark:text-white">
          WHOAMI Dashboard
        </h2>
        <div className="space-y-4 text-xl">
          <div className="flex items-center space-x-3">
            <IconUsercircle className="h-5 w-5 text-gray-500 dark:text-gray-400" />
            <div className="text-gray-700 dark:text-gray-300">
              Preferred Name:{" "}
              <span className="font-medium text-gray-900 dark:text-white">
                {nickname}
              </span>
            </div>
          </div>
          <div className="flex items-center space-x-3">
            <IconClock className="h-5 w-5 text-gray-500 dark:text-gray-400" />
            <div className="text-gray-700 dark:text-gray-300">
              Access Token Expiry:{" "}
              <span className="font-medium text-gray-900 dark:text-white">
                {expiration}
              </span>
            </div>
          </div>
          {groups.length > 0 && (
            <div className="flex flex-col space-y-1">
              <div className="font-medium text-gray-700 dark:text-gray-300">
                Groups:
              </div>
              <div className="flex flex-wrap gap-2">
                {groups.map((group, index) => (
                  <Badge key={group} variant={"outline"} className="text-sm">
                    {group}
                  </Badge>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function IconClock(props: { className?: string }) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>
  );
}

function IconUsercircle(props: { className?: string }) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="10" r="3" />
      <path d="M7 20.662V19a2 2 0 0 1 2-2h6a2 2 0 0 1 2 2v1.662" />
    </svg>
  );
}
